#!/usr/bin/env node
/**
 * Generate the markdown copy of the sheet's README tab.
 *
 * Reads README_ROWS straight out of Build.gs — the same array the spreadsheet
 * is built from — so the two cannot drift. Nothing in Build.gs executes at load
 * time, so it can simply be eval'd.
 *
 *   node scripts/draft-board/export_readme.js > docs/draft-board/cheat-sheet.md
 */
const fs = require('fs');
const path = require('path');

const here = __dirname;
eval(fs.readFileSync(path.join(here, 'Build.gs'), 'utf8'));

const isSection = (l) => README_SECTIONS.indexOf(l) !== -1;
const isStep = (l) => README_STEPS.indexOf(l) !== -1;
const esc = (s) => String(s).trim().replace(/\|/g, '\\|');

// Split the flat row list into blocks, one per heading.
const blocks = [];
let current = null;
for (const [name, formula, meaning] of README_ROWS) {
  if (isSection(name) || isStep(name)) {
    current = { heading: name, level: isSection(name) ? 2 : 3, rows: [] };
    blocks.push(current);
    continue;
  }
  if (!name && !formula && !meaning) continue;      // spacer
  if (!current) { blocks.push(current = { heading: null, level: 0, rows: [] }); }
  current.rows.push([name, formula, meaning]);
}

const out = [];
out.push('# ' + README_ROWS[0][0]);
out.push('');
out.push('> Generated from `scripts/draft-board/Build.gs` by');
out.push('> `scripts/draft-board/export_readme.js`. This mirrors the **README tab** of the');
out.push('> draft board spreadsheet exactly — edit `README_ROWS` in `Build.gs`, then');
out.push('> regenerate. Do not edit this file by hand.');
out.push('');
out.push(README_ROWS[1][0]);
out.push('');

for (const b of blocks) {
  if (!b.rows.length && !b.heading) continue;
  // Row 1 is the title and row 2 the subtitle; both are already emitted above.
  b.rows = b.rows.filter((r) => r[0] !== README_ROWS[0][0] && r[0] !== README_ROWS[1][0]);
  if (!b.rows.length && !b.heading) continue;

  if (b.heading) { out.push('#'.repeat(b.level) + ' ' + b.heading); out.push(''); }

  // Some blocks carry a lone lead-in sentence rather than named rows.
  const lead = b.rows.filter((r) => !r[0] && !r[1] && r[2]);
  lead.forEach((r) => { out.push(esc(r[2])); out.push(''); });
  const rows = b.rows.filter((r) => r[0]);
  if (!rows.length) continue;

  const withFormula = rows.some((r) => r[1] && String(r[1]).trim());
  if (withFormula) {
    out.push('| | Formula | What it means |');
    out.push('|---|---|---|');
    rows.forEach((r) => out.push(
      '| **' + esc(r[0]) + '** | `' + esc(r[1]) + '` | ' + esc(r[2]) + ' |'));
  } else {
    out.push('| | |');
    out.push('|---|---|');
    rows.forEach((r) => out.push('| **' + esc(r[0]) + '** | ' + esc(r[2]) + ' |'));
  }
  out.push('');
}

process.stdout.write(out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n');
